apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devopscloud-ubuntu-cluster
  region: eu-west-2
  version: "1.20"
managedNodeGroups:
- name: primary
  amiFamily: Ubuntu2004
  instanceType: t2.small
  minSize: 2
  maxSize: 4
  spot: true