apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devopscloud-mixed-cluster
  region: eu-west-2
  version: "1.20"
managedNodeGroups:
- name: linux
  amiFamily: Ubuntu2004
  instanceType: t2.medium
  minSize: 3
  maxSize: 6
  spot: true
nodeGroups:
- name: windows
  amiFamily: WindowsServer2019FullContainer
  instanceType: t2.medium
  minSize: 3
  maxSize: 6
  spot: true
